Upgrade code to 2020 style buiild PASS on node v6, v8, v10, v12, v14
xinkaiwang/rpio-pwm pull request #4
Opened 2020-06-14 07:57 UTC by UrielCh

Hi,

Since I do not have any oscilloscope / working testing hardware, I can not test if may change work properly.

I would like to control some SK6812 LED strip directly from nodeJS, but I'm a newbie on this hardware part.

2020-08-16 23:02 UTC, xinkaiwang requested changes
Thanks for your contribution. Over all looks great. 
Can you please change it back to base+offset then I will approve this PR?

2020-08-16 23:02 UTC, xinkaiwang commented on mailbox.c
> +   unsigned pagemask = ~0UL ^ (getpagesize() - 1);
Where is this getpagesize() get defined? What is the benefit of changing PAGE_SIZE into a function?

2020-08-16 23:02 UTC, xinkaiwang commented on mailbox.c
> +   void *mem = mmap(0, size, PROT_READ | PROT_WRITE, MAP_SHARED, mem_fd, base & pagemask);
Is this a bug fix or defensive coding?
 (base) -> (base&pagemask).  
It's not very clear to me whether this change behavior or not. Inn general, I would avoid mixing formatting change with other kind of code change in the same PR.

2020-08-16 23:02 UTC, xinkaiwang commented on mailbox.c
> +   void *mem = mmap(0, size, PROT_READ | PROT_WRITE, MAP_SHARED, mem_fd, base & pagemask);
OK, got it, you prefer to use same `base` + 2 different mask (pagemask, offsetmask) to replace base + offset. 
personally I feel the old style is simpler for reader and less error prone.

2020-08-17 18:11 UTC, UrielCh commented on mailbox.c
> +   unsigned pagemask = ~0UL ^ (getpagesize() - 1);
I took a lot a version of mailbox.c over github, to pick and merge the best part of the code.

2020-08-27 20:33 UTC, UrielCh commented
extra Mask stuff removed.

2022-12-27 02:17 UTC, merged

2022-12-27 06:29 UTC, UrielCh commented
yeeeh merged !!